const { Item } = require('../models');

const itemData = [
  {
    category: 'Game',
    name: 'Hollow Knight',
    info: 'Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.',
    year: 2017,
    url: 'https://www.giantbomb.com/a/uploads/original/24/240391/3355540-co1rgi.png',
  },
  {
    category: 'Game',
    name: 'NeverSong',
    info: 'Help little Peet hack-and-slash his way through a beautifully haunting coma. A hand-drawn action-adventure through a dreamy world filled with fleshy monsters, insane grown-ups, and sad children looking for their mommies.',
    year: 2019,
    url: 'https://www.giantbomb.com/a/uploads/original/10/103881/3188864-3188595-neversong-artwork-key-art%20%281%29.jpg',
  },
  {
    category: 'Game',
    name: 'GTA-5',
    info: 'Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.',
    year: 2013,
    url: 'https://www.giantbomb.com/a/uploads/original/0/1992/3368076-0574460249-GTAV-product-master-01-en-3mar22.jpg',
  },
  {
    category: 'Game',
    name: 'Elden Ring',
    info: 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    year: 2022,
    url: 'https://www.giantbomb.com/a/uploads/scale_medium/0/1992/3365871-1050660724-phvVT.png',
  },
  {
    category: 'Game',
    name: "Marvel's Spider-Man",
    info: 'In Marvel’s Spider-Man Remastered, the worlds of Peter Parker and Spider-Man collide in an original action-packed story. Play as an experienced Peter Parker, fighting big crime and iconic villains in Marvel’s New York. Web-swing through vibrant neighborhoods and defeat villains with epic takedowns.',
    year: 2018,
    url: 'https://www.giantbomb.com/a/uploads/scale_medium/0/3699/3037524-marvel%27s%20spider-man.jpg',
  },
  {
    category: 'Movie',
    name: 'The Godfather',
    info: "Widely regarded as one of the greatest films of all time, this mob drama, based on Mario Puzo's novel of the same name, focuses on the powerful Italian-American crime family of Don Vito Corleone (Marlon Brando). When the don's youngest son, Michael (Al Pacino), reluctantly joins the Mafia, he becomes involved in the inevitable cycle of violence and betrayal",
    year: 1972,
    url: 'https://w0.peakpx.com/wallpaper/508/93/HD-wallpaper-the-godfather.jpg',
  },
  {
    category: 'Movie',
    name: 'The Shawshank Redemption',
    info: "Andy Dufresne (Tim Robbins) is sentenced to two consecutive life terms in prison for the murders of his wife and her lover and is sentenced to a tough prison. However, only Andy knows he didn't commit the crimes. While there, he forms a friendship with Red (Morgan Freeman), experiences brutality of prison life, adapts, helps the warden, etc., all in 19 year",
    year: 1994,
    url: 'https://w0.peakpx.com/wallpaper/193/151/HD-wallpaper-shawshank-morgan-man-the-shawshank-redemption.jpg',
  },
  {
    category: 'Movie',
    name: 'Pulp Fiction',
    info: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    year: 1994,
    url: 'https://w0.peakpx.com/wallpaper/747/157/HD-wallpaper-pulp-fiction-red-black-hair.jpg',
  },
  {
    category: 'Movie',
    name: '2001: A Space Odyssey',
    info: 'After uncovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter to find its origins: a spacecraft manned by two men and the supercomputer HAL 9000.',
    year: 1968,
    url: 'https://w0.peakpx.com/wallpaper/344/84/HD-wallpaper-2001-a-space-odyssey.jpg',
  },
  {
    category: 'Movie',
    name: 'Citizen Kane',
    info: "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: 'Rosebud.'",
    year: 1941,
    url: 'https://w0.peakpx.com/wallpaper/99/9/HD-wallpaper-movie-citizen-kane.jpg',
  },
  {
    category: 'TV',
    name: '24 S1',
    info: ' 24 is a serial drama starring Kiefer Sutherland as central character Jack Bauer, an agent with the Counter Terrorist Unit (CTU), whose mandate is to protect the United States from terrorist plots. The episodes take place over the course of one hour, depicting events as they happen, in real time.',
    year: 2001,
    url: 'https://w0.peakpx.com/wallpaper/667/187/HD-wallpaper-24-official-1-fox-jack-bauer-taxi-twenty-four-tv-24.jpg',
  },
  {
    category: 'TV',
    name: 'The Friends S1',
    info: 'Comedy series about a tight-knit group of friends living in Manhattan. It also covers their interactions with their families, their lovers, and various colleagues over a period of several years. The series opens with runaway bride Rachel Green, who has just abandoned her fiance Barry Farber at the altar',
    year: 1994,
    url: 'https://w0.peakpx.com/wallpaper/410/199/HD-wallpaper-friends-friends-tv-show.jpg',
  },
  {
    category: 'TV',
    name: 'Walking Dead S1',
    info: 'The series features a large ensemble cast as survivors of a zombie apocalypse trying to stay alive under near-constant threat of attacks from zombies chiefly known as "walkers" by the other characters.',
    year: 2010,
    url: "https://w0.peakpx.com/wallpaper/560/576/HD-wallpaper-the-walking-dead-walking-dead.jpg",
  },

  {
    category: 'TV',
    name: 'Breaking Bad S1',
    info: 'Set in Albuquerque, New Mexico, between 2008 and 2010, Breaking Bad follows Walter White, a struggling, frustrated high school chemistry teacher who transforms into a ruthless kingpin in the local methamphetamine drug trade, driven to provide for his family financially after being diagnosed with inoperable lung cancer.',
    year: 2008,
    url: 'https://w0.peakpx.com/wallpaper/252/484/HD-wallpaper-breaking-bad-bad-breaking-walter.jpg',
  },
  {
    category: 'TV',
    name: 'Game of Thrones S1',
    info: ' Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.',
    year: 2011,
    url: 'https://w0.peakpx.com/wallpaper/953/946/HD-wallpaper-game-of-thrones-black-game-got-thrones.jpg',
  },
  {
    category: 'Game',
    name: 'Red Dead Redemption 2',
    info: "The third game in Rockstar's Wild West-themed series is a prequel to the events of Red Dead Redemption, returning to the open-world action of its predecessor.",
    year: 2019,
    url: 'https://www.giantbomb.com/a/uploads/scale_super/5/56742/3058747-5239356422-528b4.jpg',
  },
  {
    category: 'Movie',
    name: 'Harry Potter and the prisoner of azkaban',
    info: "The film follows Harry's third year at Hogwarts and his quest to uncover the truth about his past, including the connection recently-escaped Azkaban prisoner Sirius Black has to Harry and his deceased parents.",
    year: 2004,
    url: 'https://w0.peakpx.com/wallpaper/748/210/HD-wallpaper-harry-potter-harry-potter-3-magic-the-prisoner-of-azkaban.jpg',
  },
  {
    category: 'TV',
    name: 'Stranger Things S4',
    info: "Darker and denser than its predecessors, Stranger Things' fourth chapter sets the stage for the show's final season in typically bingeworthy fashion",
    year: 2022,
    url: 'https://w0.peakpx.com/wallpaper/808/740/HD-wallpaper-stranger-things-season-4.jpg',
  },
  {
    category: 'Game',
    name: 'Fallout 4',
    info: 'The Fallout series continues in a post-apocalyptic Boston, Massachusetts.',
    year: 2015,
    url: 'https://www.giantbomb.com/a/uploads/original/8/82063/2795700-2356006370-64616.jpg',
  },
  {
    category: 'Movie',
    name: 'The Lord of the Rings: The Fellowship of the Ring',
    info: 'The film tells the story of young hobbit Frodo Baggins who, accompanied by eight companions, embarks on a journey to destroy the One Ring',
    year: 2001,
    url: 'https://w0.peakpx.com/wallpaper/937/205/HD-wallpaper-lotr-mines-fellowship-frodo-gandalf-legolas-lord-of-the-rings-ring-rings-the-lord-of-the-rings-the-lotr.jpg',
  },
  {
    category: 'TV',
    name: 'The Office S1',
    info: 'Season 1 of The Office began airing on March 24, 2005, on NBC. It was based on the BBC series created by Ricky Gervais and Stephen Merchant of the same name',
    year: 2005,
    url: 'https://w0.peakpx.com/wallpaper/736/631/HD-wallpaper-tv-show-the-office-us-the-office.jpg',
  },
  {
    category: 'Game',
    name: 'Cyberpunk 2077',
    info: 'An open-world action role-playing game by CD Projekt RED based on the pen and paper RPG Cyberpunk 2020.',
    year: 2020,
    url: 'https://www.giantbomb.com/a/uploads/original/0/1992/3364934-2785547186-heade.jpg',
  },
  {
    category: 'Movie',
    name: 'The Batman',
    info: 'The Batman is a 2022 American superhero film based on the DC Comics character Batman',
    year: 2022,
    url: 'https://w0.peakpx.com/wallpaper/516/268/HD-wallpaper-batman-2022.jpg',
  },
  {
    category: 'TV',
    name: 'True Detective S1',
    info: 'In 2012, Louisiana State Police Detectives Rust Cohle and Martin Hart are brought in to revisit a homicide case they worked in 1995.',
    year: 2014,
    url: 'https://w0.peakpx.com/wallpaper/124/460/HD-wallpaper-true-detective-show-tv.jpg',
  },
  {
    category: 'Game',
    name: 'Project Zomboid',
    info: 'Isometric zombie survival, where death is inevitable and all you can hope for is to have a bullet left for your own head.',
    year: 2013,
    url: 'https://www.giantbomb.com/a/uploads/original/16/165036/3253895-pz.jpg',
  },
  {
    category: 'Movie',
    name: 'Fifty Shades of Grey',
    info: "Adaptation of E.L. James' best-selling erotic novel",
    year: 2015,
    url: 'https://w0.peakpx.com/wallpaper/980/765/HD-wallpaper-fifty-shades-of-grey.jpg',
  },
  {
    category: 'TV',
    name: 'Band of Brothers',
    info: 'Drawn from interviews with survivors of Easy Company, as well as their journals and letters, Band of Brothers chronicles the experiences of these men from paratrooper training in Georgia through the end of the war.',
    year: 2001,
    url: 'https://w0.peakpx.com/wallpaper/515/268/HD-wallpaper-band-of-brothers-band-band-o-brothers-brothers-of.jpg',
  },
  {
    category: 'Game',
    name: 'Rust',
    info: "From the makers of Garry's Mod, Rust is a multiplayer survival game with combat elements.",
    year: 2018,
    url: 'https://www.giantbomb.com/a/uploads/original/5/56742/2998286-header.jpg',
  },
  {
    category: 'Movie',
    name: 'The Lion King',
    info: 'The Lion King follows the epic, African adventure of a young lion called Simba as he struggles to accept the responsibilities of adulthood and his destined role as king of the jungle.',
    year: 1994,
    url: 'https://w0.peakpx.com/wallpaper/820/501/HD-wallpaper-lion-king-1994-the-lion-king-lion-movies-disney-simba-deviantart.jpg',
  },
  {
    category: 'TV',
    name: 'The Wire',
    info: 'The series expands its  focus into the media - specifically the role of newspapers in big-city bureaucracy - as it follows a newspaper staff struggling to maintain integrity and meet deadlines in the face of budget cuts and staff reductions.',
    year: 2002,
    url: 'https://w0.peakpx.com/wallpaper/733/707/HD-wallpaper-tv-show-the-wire.jpg',
  },
  {
    category: 'TV',
    name: 'Squid Game',
    info: 'The series revolves around a secret contest where 456 players, all of whom are in deep financial hardship, risk their lives to play a series of deadly games',
    year: '2021',
    url: 'https://w0.peakpx.com/wallpaper/668/371/HD-wallpaper-squid-games-squid-games.jpg',
  },

  {
    category: 'Movie',
    name: 'The Matrix',
    info: 'Depicts a dystopian future in which humanity is unknowingly trapped inside the Matrix, a simulated reality that intelligent machines have created to distract humans',
    year: '1999',
    url: 'https://w0.peakpx.com/wallpaper/668/945/HD-wallpaper-the-matrix-1999-movie-1999-film-the-matrix-actors.jpg',
  },
  {
    category: 'Game',
    name: 'Super Mario Bros',
    info: 'The game is based on a series of side-scrolling levels, each filled with enemies ranging from mushroomlike Goombas to evil turtles known as Koopa Troopas.',
    year: '1985',
    url: 'https://www.giantbomb.com/a/uploads/scale_super/9/93770/2362268-nes_supermariobros_eu.jpg',
  },
  {
    category: 'TV',
    name: 'Chernobyl',
    info: 'Chernobyl is a historical drama television miniseries that revolves around the Chernobyl disaster of 1986 and the cleanup efforts that followed',
    year: '2019',
    url: 'https://w0.peakpx.com/wallpaper/292/681/HD-wallpaper-chernobyl-1986-abej-beograd.jpg',
  },
  {
    category: 'Movie',
    name: 'Mad Max: Fury Road',
    info: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper and a drifter named Max.',
    year: '2015',
    url: 'https://w0.peakpx.com/wallpaper/104/277/HD-wallpaper-mad-max-fury-road-movie-mad-max-fury-road-movies.jpg',
  },
  {
    category: 'Game',
    name: 'Sonic the hedgehog',
    info: 'Sonic is an anthropomorphic blue hedgehog who can run at supersonic speeds and curl into a ball to attack enemies.',
    year: '1991',
    url: 'https://www.giantbomb.com/a/uploads/original/0/3693/609697-ss_08.27.2008_08.57.11pm.jpg',
  },
  {
    category: 'Movie',
    name: 'No Hard Feelings',
    info: "On the brink of losing her childhood home, a desperate woman agrees to date a wealthy couple's introverted and awkward 19-year-old son. However, he proves to be more of a challenge than she expected, and time is running out before she loses it all.",
    year: '2023',
    url: 'https://blog.flicks.co.nz/wp-content/uploads/No-Hard-Feelings.jpg',
  },
  {
    category: 'Movie',
    name: 'Operation Fortune: Ruse de Guerre',
    info: "Elite spy Orson Fortune must track down and stop the sale of a deadly new weapons technology wielded by billionaire arms broker Greg Simmonds. Reluctantly teamed up with some of the world's best operatives, Fortune and his crew recruit Hollywood's biggest movie star, Danny Francesco, to help them on their globe-trotting mission to save the world.",
    year: '2023',
    url: 'https://images8.alphacoders.com/119/1196019.jpg',
  },
  {
    category: 'Movie',
    name: 'Indiana Jones and the Dial of Destiny',
    info: 'Daredevil archaeologist Indiana Jones races against time to retrieve a legendary dial that can change the course of history. Accompanied by his goddaughter, he soon finds himself squaring off against Jürgen Voller, a former Nazi who works for NASA.',
    year: '2023',
    url: 'https://thecrimsonwhite.com/wp-content/uploads/2023/07/FxbxEb9aEAAqpOS.webp',
  },
  {
    category: 'Movie',
    name: 'Fast X',
    info: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted and outdriven every foe in their path. Now, they must confront the most lethal opponent they've ever faced. Fueled by revenge, a terrifying threat emerges from the shadows of the past to shatter Dom's world and destroy everything -- and everyone -- he loves.",
    year: '2023',
    url: 'https://m.media-amazon.com/images/I/81cwbLBVDbL.jpg',
  },
  {
    category: 'Movie',
    name: 'Three Thousand Years of Longing',
    info: "While attending a conference in Istanbul, Dr. Alithea Binnie happens to encounter a djinn who offers her three wishes in exchange for his freedom. This presents two problems: first, she doubts that he's real, and second, because she's a scholar of story and mythology, she knows all the cautionary tales of wishes gone wrong. The djinn pleads his case by telling her fantastical stories of his past. Eventually, she's beguiled and makes a wish that surprises them both.",
    year: '2022',
    url: 'https://www.movieposters.com/cdn/shop/products/three_thousand_years_of_longing_480x.progressive.jpg?v=1656957331',
  }, 
  {
    category: 'Movie',
    name: 'Wrath of the Titans',
    info: 'Perseus, a demigod, has to rescue his father, Zeus, who is held captive by Ares and Hades. However, he has to defeat not only his brother and uncle but also the Titans with whom they have partnered.',
    year: '2012',
    url: 'https://images.moviesanywhere.com/3b8e360d423e1fb84824378417f164c7/13cd9fdf-d136-40fe-b01d-07622eee615e.jpg',
  }, 
  {
    category: 'Movie',
    name: 'The Flash',
    info: "Based on the DC superhero character.Worlds collide when the Flash uses his superpowers to travel back in time to change the events of the past. However, when his attempt to save his family inadvertently alters the future, he becomes trapped in a reality in which General Zod has returned, threatening annihilation. With no other superheroes to turn to, the Flash looks to coax a very different Batman out of retirement and rescue an imprisoned Kryptonian -- albeit not the one he's looking for.",
    year: '2023',
    url: 'https://i.ebayimg.com/images/g/hxAAAOSwZl9kr7Lk/s-l1600.jpg',
  }, 
  {
    category: 'Movie',
    name: 'The amazing Maurice',
    info: 'Maurice is a streetwise ginger cat who comes up with a money-making scam by befriending a group of self-taught talking rats. When Maurice and the rodents meet a bookworm called Malicia, their little con soon goes down the drain.',
    year: '2023',
    url: 'https://m.media-amazon.com/images/I/919np1KDsrL.jpg',
  },
  {
    category: 'Movie',
    name: 'Avatar: The Way of Water',
    info: "Jake Sully and Ney'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora. When an ancient threat resurfaces, Jake must fight a difficult war against the humans.",
    year: '2022',
    url: 'https://www.movieposters.com/cdn/shop/products/avatar-the-way-of-water-teaser-one-sheet-wall-poster-rp23164-1_480x.progressive.png.jpg?v=1673982224',
  },
  {
    category: 'Movie',
    name: 'Shang-Chi and the Legend of the Ten Rings',
    info: 'Shang-Chi, a martial artist, lives a quiet life after he leaves his father and the shadowy Ten Rings organisation behind. Years later, he is forced to confront his past when the Ten Rings attack him.',
    year: '2021',
    url: 'https://www.movieposters.com/cdn/shop/products/shangchi_and_the_legend_of_the_ten_rings_480x.progressive.jpg?v=1622220347',
  },
  {
    category: 'TV',
    name: 'Silo',
    info: 'In a ruined and toxic future, a community exists in a giant underground silo that plunges hundreds of stories deep; there, people live in a society full of regulations they believe are meant to protect them.',
    year: '2023',
    url: 'https://www.apple.com/tv-pr/articles/2023/06/apple-tv-renews-hit-world-building-drama-silo-for-season-two/images/big-image/big-image-01/061323_Silo_Season_Two_Announcement_Post_Big_Image_01_big_image_post.jpg.large_2x.jpg',
  },
  {
    category: 'Movie',
    name: 'Dune',
    info: 'Paul Atreides arrives on Arrakis after his father accepts the stewardship of the dangerous planet. However, chaos ensues after a betrayal as forces clash to control melange, a precious resource.',
    year: '2021',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdyqth6HHo_nd11vcFap2u3kcwkNXvzCo8-NyWTXGheg&s',
  },
  {
    category: 'Movie',
    name: 'Unhinged',
    info: 'Rachel gets into a small argument with the stranger on the road. But the man turns out to be mentally unstable and makes her a target of his rage, killing and injuring several people..',
    year: '2020',
    url: 'https://m.media-amazon.com/images/I/61MFsVi263L._AC_SX679_.jpg',
  },
  {
    category: 'Movie',
    name: 'Parasite',
    info: 'The struggling Kim family sees an opportunity when the son starts working for the wealthy Park family. Soon, all of them find a way to work within the same household and start living a parasitic life.',
    year: '2019',
    url: 'https://m.media-amazon.com/images/I/81hsswTfQXL.__AC_SX300_SY300_QL70_ML2_.jpg',
  },
  {
    category: 'Movie',
    name: 'Antebellum',
    info: "Successful author Veronica Henley is finishing a book tour before she returns home to her husband and daughter. But a shocking turn of events is about to upend Veronica's existence, plunging her into a horrifying reality that forces her to confront her past, present and future -- before it's too late.",
    year: '2020',
    url: 'https://www.imdb.com/title/tt10065694/mediaviewer/rm4292455681/?ref_=tt_ov_i',
  },
  {
    category: 'Movie',
    name: 'Tenet',
    info: 'When a few objects that can be manipulated and used as weapons in the future fall into the wrong hands, a CIA operative, known as the Protagonist, must save the world.',
    year: '2020',
    url: 'https://i.ebayimg.com/images/g/XPwAAOSwMYRfU0F9/s-l1600.jpg',
  },
  {
    category: 'Movie',
    name: '1917',
    info: "During World War I, two British soldiers -- Lance Cpl. Schofield and Lance Cpl. Blake -- receive seemingly impossible orders. In a race against time, they must cross over into enemy territory to deliver a message that could potentially save 1,600 of their fellow comrades -- including Blake's own brother.",
    year: '2019',
    url: 'https://w0.peakpx.com/wallpaper/165/584/HD-wallpaper-1917-poster-1917-film-movie-poster-skyfall-theme-thing-traveler-wall-war.jpg',
  },  
  {
    category: 'Movie',
    name: 'Hamilton',
    info: 'The original Broadway production of the award-winning musical that tells the story of Alexander Hamilton, first secretary of the treasury, blending hip-hop, jazz, R&B, and Broadway styles, filmed from the Richard Rogers Theater in New York.',
    year: '2020',
    url: 'https://i0.wp.com/www.nerdsandbeyond.com/wp-content/uploads/2020/07/MV5BMWVhM2RhZTMtYjk2Mi00YjJlLTg4ZTEtNjBmYzBlMTZlMmI0XkEyXkFqcGdeQXVyNTk5NTQzNDI@._V1_SY1000_CR006661000_AL_.jpg?fit=666%2C1000&ssl=1',
  },  
  {
    category: 'Movie',
    name: 'Run',
    info: 'Chloe, a homeschooled teenager, is forbidden from seeing the mail and is kept in isolation. She soon starts suspecting her mother of keeping dark secrets and decides to investigate.',
    year: '2020',
    url: 'https://i0.wp.com/vanessasnonspoilers.com/wp-content/uploads/2021/04/Run-Movie-Poster-courtesy-of-GEM-Entertainment.jpg?fit=961%2C604&ssl=1',
  },  
  {
    category: 'Movie',
    name: ' A Beautiful Day In The Neighbourhood',
    info: "When a few objects that can be manipulated and used as weapons in the future fall into the wrong hands, a CIA operative, known as the Protagonist, must save the world.",
    year: '2023', 
    url: 'https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/chameleon/title-movie/DP_4889551_TC_1400x2100_DP_4889540_A_BEAUTIFUL_DAY_IN_THE_NEIGHBORHOOD_2000x3000_EST_0.jpg?itok=nQ1AlvcI',
  },  
  {
    category: 'Movie',
    name: 'Host',
    info: 'Six friends accidentally invite the attention of a demonic presence during an online séance and begin noticing strange occurrences in their homes.',
    year: '2020',
    url: 'https://images.saymedia-content.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:eco%2Cw_1200/MTc2Mjg3NTc5ODYyNDEwNDEz/host-2020-movie-review.jpg',
  },  
  {
    category: 'Movie',
    name: 'Jojo Rabbit',
    info: 'Hitler Youth cadet Jojo Betzler firmly believes in the ideals of Nazism manifested by his imaginary friend, Adolf Hitler. However, his foundations are shaken when he finds a Jewish girl in his house.',
    year: '2019',
    url: 'https://themoviemylife.files.wordpress.com/2019/07/jojo-rabbit-2019-scarlett-johansson-fox-searchlight.png',
  },  
  {
    category: 'TV',
    name: 'Severance',
    info: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives; when a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.',
    year: '2022',
    url: 'https://images4.alphacoders.com/130/thumbbig-1301272.webp',
  },  
  {
    category: 'Movie',
    name: 'Saint Maud',
    info: "Maud is a reclusive young nurse whose impressionable demeanour causes her to pursue a pious path of Christian devotion after an obscure trauma. Now charged with the hospice care of Amanda, a retired dancer ravaged by cancer, Maud's fervent faith quickly inspires an obsessive conviction that she must save her ward's soul from eternal damnation, whatever the cost.",
    year: '2019',
    url: 'https://m.media-amazon.com/images/I/81ts-Ai6dBL._AC_SY879_.jpg',
  },  
  {
    category: 'Movie',
    name: 'Rocks',
    info: "A determined teenage girl struggles to take care of herself and her younger brother after her mother's abrupt departure.",
    year: '2019',
    url: 'https://media-cache.cinematerial.com/p/500x/bwpnwrgu/rocks-swedish-movie-poster.jpg?v=1607533734',
  },  
  {
    category: 'Movie',
    name: 'Portrait Of A Lady On Fire',
    info: 'France, 1770. Marianne, a painter, is commissioned to do the wedding portrait of Héloïse, a young woman who has just left the convent. Héloïse is a reluctant bride to be and Marianne must paint her without her knowing. She observes her by day, to paint her secretly.',
    year: '2019',
    url: 'https://www.hometheaterforum.com/community/media/2019-portrait-of-a-lady-on-fire-poster-jpg.6226/full',
  },  
  {
    category: 'Movie',
    name: 'Uncut Gems',
    info: 'A charismatic jeweller makes a high-stakes bet that could lead to the windfall of a lifetime. In a precarious high-wire act, he must balance business, family and adversaries on all sides in pursuit of the ultimate win.',
    year: '2019',
    url: 'https://m.media-amazon.com/images/I/81sHvqcGALL.__AC_SX300_SY300_QL70_ML2_.jpg',
  },  
  {
    category: 'TV',
    name: 'RFDS',
    info: 'The workers of the Royal Flying Doctor Service of Australia face many obstacles every day, but with the support of each other, they solve the problems.',
    year: '2021',
    url: 'https://image.pbs.org/contentchannels/hEPWbCZ-show-poster2x3-9DWvVNk.jpg',
  },  


];

const seedItems = () => Item.bulkCreate(itemData);

module.exports = seedItems;
